# Example configuration for database.
#
# To use on your development environment,
# copy this file as config/database.yml and modify at your will.
#
# Your local config/database.yml file is added to .gitignore and
# wont be uploaded to the repo.

defaults: &defaults
  adapter: postgresql
  encoding: utf8
  database: timeoverflow_<%= ENV["RAILS_ENV"] || ENV["RACK_ENV"]  || "development" %>
  host: localhost
  pool: 5

development:
  <<: *defaults

test:
  <<: *defaults
  database: timeoverflow_test
