send_push_notifications_job:
  cron: 'every 5 minutes'
  class: 'SendPushNotificationsJob'
  queue: cron
weekly_digest:
  cron: 'every monday at 9am'
  class: 'OrganizationNotifierJob'
  queue: cron
membership_warning:
  cron: 'every day at 10am'
  class: 'MembershipWarningJob'
  queue: cron
