---
# Thanks to https://allysonjulian.com/setting-up-docker-with-xhyve/
- name: Install xhyve and dependencies
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - xhyve
    - docker
    - docker-compose
    - docker-machine

- name: Download hyve driver for docker
  get_url:
    url: https://github.com/zchee/docker-machine-driver-xhyve/releases/download/v0.2.2/docker-machine-driver-xhyve
    dest: /usr/local/bin/docker-machine-driver-xhyve
    checksum: "sha1:9af9650a697336f1b00ef64475d7ee952d66b9f3"

- name: Adjust u/g/mode for hyve driver
  # Cannot merge with above, because the download is not rolled back if
  # the file actions fail for any reason.
  # See issue at https://github.com/ansible/ansible/issues/11821
  become: yes
  file:
    path: /usr/local/bin/docker-machine-driver-xhyve
    owner: root
    group: admin
    mode: ug+x,u+s

# NEVER EVER EVER DO THIS:
# - name: Add current user to the wheel group
#   become: yes
#   user:
#     name: "{{ ansible_user_id }}"
#     append: yes
#     groups: wheel
#
# It will remove most groups that come from DirectoryServices, like 'admin'
# so the user will not be and administrator anymore. Luckily I had another user
# with admin credentials here....
